FIX Don't display element actions to user if they cant select them
silverstripe/silverstripe-elemental pull request #874
Opened 2021-02-14 23:28 UTC by emteknetnz

Fix for https://github.com/dnadesign/silverstripe-elemental/issues/856

Original PR https://github.com/dnadesign/silverstripe-elemental/pull/858

2021-02-21 23:47 UTC, emteknetnz commented
@clarkepaul This is a different PR from the [related PR](https://github.com/dnadesign/silverstripe-elemental/pull/877) where there was a UX discussion.

In this PR the options that cannot be selected are simply removed.  Since the work is already done here the cost to implement is significantly less.

If you'd still like the work done as per https://github.com/dnadesign/silverstripe-elemental/pull/877#issuecomment-782950166 then let me know, and we'll look to update this PR instead.  Not sure about complexity level though, it may push the timeline on this one back.

2021-02-22 01:35 UTC, clarkepaul commented
I'm not sure why the _Unpublish_ action is visible to a user that only has CanView permissions, seems wrong to me.

Because the availability of these block actions are based on permissions, we do need to let people know that. In that the UI looks different for them, and acts differently from what the user guides show. At least they will be able to ask for permissions to the admin.
I think my suggestion for having the action disabled still makes the most sense, the following should be possible:

_Duplicate_ action:
- "Duplicate" to be italicised and use the lighter text colour variable (muted)
- when hovering link shows not allowed cursor
- title text on hover to says "Duplicate, insufficient permissions"

_Archive_ action:
- "Archive" to be italicised and use the lighter text colour variable (muted)
- when hovering link shows not allowed cursor
- title text on hover to says "Archive, insufficient permissions"

I think the same should be able to apply to _Publish_, but _Unpublish_ is okay to hide if a block is only in draft.

I realise these patterns might not be exactly the same in other areas of the CMS but we should aim for best practices/UX.

Side note those readonly fields look pretty wack, which browser are you using @emteknetnz ?

2021-02-22 03:42 UTC, emteknetnz commented
Firefox for linux

2021-02-22 22:27 UTC, emteknetnz commented
OK, have implemented as requested.

I couldn't get both the tooltip and cursor in the same screenshot so I've taken 2

**Disabled action**

![image](https://user-images.githubusercontent.com/4809037/108778063-b0cc7e00-75c9-11eb-8a94-a0b7fdef225e.png)

**Mouse over cursor**

![Screenshot_20210223_112606](https://user-images.githubusercontent.com/4809037/108778367-25072180-75ca-11eb-838a-3be8f1ce9326.png)

2021-02-22 22:54 UTC, clarkepaul commented
I think it's perfect thanks

2021-02-23 22:44 UTC, dnsl48 requested changes
Looks good overall!
Just one note regarding the translation key namings.

2021-02-23 22:44 UTC, dnsl48 commented on client/lang/src/en.json
> +  "ElementArchiveAction.ARCHIVE_DISABLED": "Archive, insufficient permissions",
`ARCHIVE_DISABLED` key name does not imply any relevance with lacking permission.
(`disabled` conventionally means the feature is off altogether, not something perms related).
Feels like we might use a different name that could be more relevant to the use case (`canArchive` permission check)

2021-02-23 22:44 UTC, dnsl48 commented on client/lang/src/en.json
> +  "ElementArchiveAction.DUPLICATE_DISABLED": "Duplicate, insufficient permissions",
`DUPLICATE_DISABLED` key relevance with permissions (same as ARCHIVE_DISABLED - see above)

2021-02-23 22:44 UTC, dnsl48 commented on client/lang/src/en.json
> +  "ElementPublishAction.PUBLISH_DISABLED": "Publish, insufficient permissions",
`PUBLISH_DISABLED` key relevance with permissions (same as ARCHIVE_DISABLED - see above)

2021-02-23 22:44 UTC, dnsl48 commented on client/lang/src/en.json
> +  "ElementUnpublishAction.UNPUBLISH_DISABLED": "Unpublish, insufficient permissions",
`UNPUBLISH_DISABLED` key relevance with permissions (same as ARCHIVE_DISABLED - see above)

2021-02-23 22:48 UTC, dnsl48 commented
## Merge Checklist

This list helps to ensure that PRs are in a good state before merging. Ideally it should be applied to the PR upon
initial triage, so that the contributor can check items off prior to the reviewer digging in. Some items may not be
relevant to every PR, and can be crossed out on a case-by-case basis.

* [x] The target branch is [correct](https://docs.silverstripe.org/en/4/contributing/code/#picking-the-right-version)
* [x] All commits are relevant to the change (e.g. no debug statements or arbitrary linting)
* [x] The commit messages follow [the contribution guidelines](https://docs.silverstripe.org/en/4/contributing/code/#commit-messages)
* [x] The patch follows [the contribution guidelines](https://docs.silverstripe.org/en/4/contributing/code/)
* [x] New features are covered with tests (back-end with unit tests, front-end with Behat)
* [ ] ~Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the
      changelog for the intended release~
* [x] CI is green
* [ ] At least one peer reviewer approved; no outstanding changes requested

2021-02-24 20:59 UTC, dnsl48 approved these changes

2021-02-24 20:59 UTC, merged