DEP Update eslint-config
silverstripe/silverstripe-elemental pull request #962
Opened 2022-03-10 19:59 UTC by emteknetnz

Issue https://github.com/silverstripe/eslint-config/issues/9

2022-03-11 00:31 UTC, maxime-rainville requested changes
I pulled this PR down and ran and build. The `yarn.lock` file was updated to reflect the new devDependency.

How come the `yarn.lock` file hasn't been updated? And why isn't the Travis build failing ... it's meant to detect this kind of oversight?

2022-03-11 00:39 UTC, emteknetnz commented
We're not updating deps here (updating yarn.lock).  What we're doing is making it so the next time `yarn upgrade` is run, it will update the version of eslint-config

There's no material difference between eslint-config 0.0.6 and 0.1.0.  The only different is that if we release 0.1.1, the ^ caret now means that asset-admin etc will get 0.1.1.  Previously with ^0.0.6 the caret effectively did nothing.

2022-03-11 00:50 UTC, emteknetnz commented
Have updated PR after running `yarn install`

2022-03-25 02:49 UTC, maxime-rainville approved these changes

2022-03-25 02:49 UTC, merged