ENH Render some buttons for blocks that can not be edited inline
silverstripe/silverstripe-elemental pull request #963
Opened 2022-03-19 10:59 UTC by maxime-rainville

Some block types can not be edited in an Elemental Area (e.g.: UserForm blocks). Current behaviour is to not render any actions for those blocks in the Elemental Area.

However some action still make sense in that context (e.g.: Duplicate, Archive, Unpublish).

This PR allows those extra actions to be displayed.

# Parent issue
- Fixes https://github.com/silverstripe/silverstripe-elemental/issues/512

2022-03-19 11:04 UTC, maxime-rainville reviewed
Turns out we didn't the Context provider non-sense at all. We just needed to pass the expandable prop all the way down.

2022-03-19 11:04 UTC, maxime-rainville commented on client/src/components/ElementEditor/tests/Header-test.js
> +      expect(wrapper.text()).toContain('ElementActionsComponent');
This is shallow rendered, and it won't go all the way to rendering the actual buttons, so I can't make assertions beyond checking that its rendering the action list or not.

2022-03-22 04:09 UTC, emteknetnz requested changes
Tested locally, does what it should do.  Unpublish button remains on elemental-userforms which makes sense IMO.  Some minor changes requested

2022-03-23 04:01 UTC, emteknetnz commented on client/src/components/ElementEditor/ElementActions.js
> +        { expandable && this.renderEditTabs() }
@maxime-rainville remember to do this one

2022-03-23 04:55 UTC, maxime-rainville commented on client/src/components/ElementEditor/ElementActions.js
> -    if (editTabs && editTabs.length && React.Children.count(children)) {
I swap the return null and return DropdownItem around just so the approach between renderDivider and renderTabs are consistien

2022-03-23 04:58 UTC, maxime-rainville reviewed
I was thinking it might be nice to cover this behavior with some behat test, but we can't really do it without requiring userform and the userfrom block because that's the only block that can't be rendered inline.

2022-03-23 08:06 UTC, GuySartorelli commented
> we can't really do it without requiring userform and the userfrom block because that's the only block that can't be rendered inline.

I haven't done anything with heat tests yet so excuse my ignorance but I take it then that behat tests can't take advantage of classes that implement `TestOnly`?

2022-03-23 21:46 UTC, emteknetnz approved these changes

2022-03-23 21:46 UTC, merged

2022-03-29 21:21 UTC, maxime-rainville commented
> I haven't done anything with behat tests yet so excuse my ignorance but I take it then that behat tests can't take advantage of classes that implement TestOnly?

@GuySartorelli Exactly ... your behat test need to be run against an actual functional website. Occasionally, we'll install frameworktest so we can test specific features that are not directly used in our core modules.

2022-03-29 21:56 UTC, emteknetnz commented
@GuySartorelli example behat equivalent of a TestOnly page - https://github.com/silverstripe/silverstripe-frameworktest/blob/4/code/multitab-validation/MultiTabPage.php